import { describe, it, expect } from "vitest";
import fs from "node:fs";
import path from "node:path";
import capacitorConfig from "../../capacitor.config";

/**
 * Regression guard for Android edge-to-edge insets.
 *
 * Android 15+ (targetSdk 35+) forces the Capacitor WebView to draw underneath
 * the status bar, so app chrome used to sit under the system clock and icons.
 * Capacitor 8 handles the insets through its built-in SystemBars plugin, and
 * the web chrome has to consume the insets Capacitor exposes.
 */
describe("Android edge-to-edge safe-area insets", () => {
  const read = (relativePath: string) => fs.readFileSync(path.resolve(process.cwd(), relativePath), "utf8");

  it("does not rely on android.adjustMarginsForEdgeToEdge, which Capacitor ignores", () => {
    // That key is absent from Capacitor's Android config parser (CapConfig)
    // and from the CLI config type, so it silently did nothing.
    expect(capacitorConfig.android ?? {}).not.toHaveProperty("adjustMarginsForEdgeToEdge");
  });

  it("enables SystemBars inset handling for a viewport-fit=cover document", () => {
    const systemBars = capacitorConfig.plugins?.SystemBars;
    expect(systemBars).toBeDefined();
    // "disable" would hand inset handling back to the app and let chrome
    // overlap the system bars again.
    expect(["css", "native"]).toContain(systemBars?.insetsHandling);
    expect(systemBars?.initialViewportFitValueHint).toBe("cover");
  });

  it("ships the same SystemBars config in the Android assets", () => {
    // The assets copy is what the built APK reads, and it is regenerated by
    // `cap sync` — keeping them equal means a plain Android Studio rebuild
    // already gets correct inset handling.
    const assets = JSON.parse(read("android/app/src/main/assets/capacitor.config.json")) as {
      plugins?: { SystemBars?: unknown };
    };
    expect(assets.plugins?.SystemBars).toEqual(capacitorConfig.plugins?.SystemBars);
  });

  it("consumes both env() insets and Capacitor's injected --safe-area-inset-* variables", () => {
    const css = read("src/styles.css");
    expect(css).toContain("env(safe-area-inset-top");
    expect(css).toContain("var(--safe-area-inset-top");
    expect(css).toContain("env(safe-area-inset-bottom");
    expect(css).toContain("var(--safe-area-inset-bottom");
    // Chrome reads the resolved values through these variables only.
    expect(css).toContain("--mm-inset-top");
    expect(css).toContain("--mm-inset-bottom");
  });

  it("keeps chrome surfaces on the shared inset variables instead of bare env()", () => {
    const surfaces = [
      "src/components/music/layout/MobileHeader.tsx",
      "src/components/music/layout/MobileNav.tsx",
      "src/components/music/layout/MiniPlayer.tsx",
      "src/components/music/ui/FullScreenPlayer.tsx",
    ];
    for (const file of surfaces) {
      expect(read(file)).not.toContain("env(safe-area-inset");
    }
  });
});
